### ISSUE TITLE
Nested structures not sorted

### ISSUE THREAD

**Issue by avitova** [ilyakaznacheev/cleanenv#119]
Hello,
we are using cleanenv to generate our example config file.
When defining a more complex nested structure with prefixes, such as:
```
type config struct {
	App struct {
		Port  int `env:"PORT" env-description:"one"`
		Cache struct {
			Type  string `env:"TYPE" env-description:"one"`
			Redis struct {
				Host string `env:"HOST" env-description:"one"`
			} `env-prefix:"REDIS_"`
		} `env-prefix:"CACHE_"`
	} `env-prefix:"APP_"`
	Database struct {
		Host string `env:"HOST" env-description:"one"`
	} `env-prefix:"DATABASE_"`
}
```

We'd like to see the output sorted when generating the description, such as:
```
              APP_PORT int
                	one
              APP_CACHE_TYPE string
                	one
              APP_CACHE_REDIS_HOST string
                	one
              DATABASE_HOST string
                	one
```

Instead, the output is generated based on the nesting level, and the APP variables are split:

```
              APP_PORT int
                	one
              DATABASE_HOST string
                	one
              APP_CACHE_TYPE string
                	one
              APP_CACHE_REDIS_HOST string
                	one
```

I have not found an example of nested structures with prefixes in your example files. Therefore I wonder if such behaviour is intentional. Would you consider a change in such a direction? It would be nice to keep the related variables together. We have quite a lot of env variables with deeper nesting.
Thanks in advance

**Comment by ilyakaznacheev** [comment]
@avitova thank you for the question. No, it is not sorted. However, I see that sorting may be useful here.

**Comment by avitova** [comment]
Thank you! <3
