### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by ilyakaznacheev** [ilyakaznacheev/cleanenv#34]
Need to add more examples for different cases to `example` directory.

**Comment by arunvm123** [comment]
Is this still a requirement? I can take this up if needed. 

Maybe we can discuss and decide on a list of examples that is necessary and I can add them accordingly

**Comment by ilyakaznacheev** [comment]
Sure, this topic is still open.

I would be happy to discuss possible examples, so feel free to suggest.

**Comment by arunvm123** [comment]
I went through the example that is present in the repo, but I feel it does not focus on how to use the package. I was thinking more along the lines of small scripts, like the code snippets mentioned in the readme as examples. That would show specifically how to use the package and then the users can figure out how to integrate it into their projects. 

what do you think? @ilyakaznacheev

**Comment by ilyakaznacheev** [comment]
@arunvm123 you are right, the example shows only the basic use of the package, although there are still many useful options. Some are described in README, most are described in tests and examples in godoc, but it would be convenient to implement them as examples like this one.

**Comment by arunvm123** [comment]
I am starting to understand what you mean, but can you describe another example for me to get a better grasp of it?

**Comment by ilyakaznacheev** [comment]
Sure. There are many good ways to use the library:
- parse a file; 
- parse several files into the same structure or substructures; 
- parse a file as default configs and then override with some environment variables;
- read different types of data from the environment;
- read a variable using custom reader/setter;
- use built-in help output;
- use customized help output;
- any combination of options above :)

**Comment by arunvm123** [comment]
I mean what an example would like. The current one in the directory is a web server that parses a file to read in the configuration. Similarly what would another example look like?

**Comment by eloo** [comment]
i would like to see an example of this
`parse several files into the same structure or substructures` 

at least this is a common use case in my projects

**Comment by arunvm123** [comment]
Hi @eloo,
I have opened a PR with the example you asked for, maybe you can have a look at that.

@ilyakaznacheev Can you review the code and see if the example meets you requirement, if not you can suggest changes and once we decide on a list and i add more examples, you can merge it

**Comment by ilyakaznacheev** [comment]
@arunvm123 sorry for the late response, I was a bit busy with work and other urgent stuff.

The review is done, a couple of notes. Great work!

**Comment by arunvm123** [comment]
Shall I add more examples from the list below in similar format?

- parse a file;
- parse several files into the same structure or substructures;
- parse a file as default configs and then override with some environment variables;
- read different types of data from the environment;
- read a variable using custom reader/setter;
- use built-in help output;
- use customized help output;

**Comment by ilyakaznacheev** [comment]
@arunvm123 it would be nice if you can add more examples, but it's up to you.

More necessary would be a custom reader/setter and built-in help output, I think.

They are already described somehow in `README.md` and `example_test.go`, but it may be useful to have some examples to simply copy-paste from.

**Comment by eloo** [comment]
@arunvm123 
thanks for the example.. looks good to me :)

**Comment by ilyakaznacheev** [comment]
Thanks, @arunvm123, I'll review it soon

**Comment by ilyakaznacheev** [comment]
Like it's enough examples for now, maybe I'll reopen it before hacktoberfest for more fun.
