### ISSUE TITLE
Read from multiple sources

### ISSUE THREAD

**Issue by k1ng440** [ilyakaznacheev/cleanenv#35]
Hello,
Thanks for writing this great library.

reading from multiple sources would be a great future

**Comment by ilyakaznacheev** [comment]
Thanks!
Could you give an example of the logic you're asking about?

**Comment by vlaabra** [comment]
```
cleanenv.ReadConfig("config.yml", &cfg)
cleanenv.ReadConfig("db/conf.yml", &cfg)
```

🤷‍♂️

**Comment by ilyakaznacheev** [comment]
@vlaabra that's already possible. Just read from any sources you want, just keep in mind that the last read may override the previous one if there is a common field in both sources.

**Comment by ilyakaznacheev** [comment]
Say, you have a two config files, `cfg_1.yml`:

```yaml
one: 1
```

and `cfg_2.yml`:

```yaml
two: 2
```

Then the following code

```go
	type config struct {
		One int `yaml:"one"`
		Two int `yaml:"two"`
	}

	cfg := config{}
	cleanenv.ReadConfig("cfg_1.yml", &cfg)
	cleanenv.ReadConfig("cfg_2.yml", &cfg)
	fmt.Printf("%+v", cfg)
```

will output

```bash
{One:1 Two:2}
```

Sure if there would be `one: 123` in the second file, it would rewrite the value from the first one.

Simple enough and no side-effects 😎

**Comment by ilyakaznacheev** [comment]
So, since we've figured out that it's already been implemented, I'm closing the issue.
