### ISSUE TITLE
Add default env variable binding

### ISSUE THREAD

**Issue by eloo** [ilyakaznacheev/cleanenv#55]
Hi,

i'm currently migrating from a combination of godotenv, uber-config and envconfig to your library because AFAIK your library is doing a good job integrating this loading mechanism into a single library without hastle.

But as i have already a decent config struct based on envconfig i see thats its pretty hard to add for every property an env tag (AFAIK this is needed).
So i would like to request some kind of default naming schema like envconfig has already. Further i'm missing the usage of prefixes but i've seen that there is already an issue addressing this.

For so the default naming here is short example:

``` 
type Config struct {
	Server   ServerConfig
}

type ServerConfig struct {
	Address          string
	Port                 int        `env-default:"1328"`
        FriendlyName string
}
```

Currently i would to add everywhere an `env` tag with the name.. which is mostly the same as the property.
So it would be cool if this config would be sufficient to have the env config working like this:
```
SERVER_ADDRESS=cleanenv.is.great
SERVER_PORT=1337
SERVER_FRIENDLYNAME="Yeah cleanenv is great"
``` 

What do you think? Could this be an future feature?

Thanks

**Comment by ilyakaznacheev** [comment]
@eloo The idea is good, I think about it for some time.

But there is a reason why I wouldn't want to do it: I don't want the library to act implicitly. That is, if the environment variable is read from the environment, this behavior is explicitly described in the structure tags.

But I won't close this PR to collect opinions from other users of the library, maybe for most people, it would be convenient.

**Comment by ilyakaznacheev** [comment]
So I've decided to close the issue because of no other feedback.

Yes that feature is useful, but I have bad experience with libraries "magically" combining names of environment variables.

I also would like to stay with the idea of clean and simple config (as the library name says). It may me some copy-and-paste, but the code will be easy to read and env variables will be easy to search.
