### ISSUE TITLE
Add config overriding

### ISSUE THREAD

**Issue by theArtechnology** [ilyakaznacheev/cleanenv#62]
It would be nice if we have the possibility to override a base config.

Like:

.env.override
.config.yml.override

**Comment by eloo** [comment]
I guess this can be easily achieved using the multiple files example.

Maybe you should have a look here:
https://github.com/ilyakaznacheev/cleanenv/tree/master/example/parse_multiple_files

Best regards

**Comment by ilyakaznacheev** [comment]
Yes, it's already possible, you just need to execute several config reads, each new read will override previous values with new ones (if there are new ones).

Simplest example: you are reading some default config from `config.yaml` and then overriding **some of them** from the environment or another config file.

**Comment by ilyakaznacheev** [comment]
Closed due to inactivity, probably solved.
