### ISSUE TITLE
Any plans to move to yaml v3?

### ISSUE THREAD

**Issue by marcoderama** [ilyakaznacheev/cleanenv#66]
I would like to use `yaml.Node` in my config files but have found they don't work with cleanenv.  As an experiment, I changed the import in `cleanenv.go` to use yaml v3 instead and things with `yaml.Node` started working.  I did no testing otherwise though.

So, I'm curious, any plans to move to yaml v3?

**Comment by ilyakaznacheev** [comment]
Is it backwards compatible with v2?

**Comment by marcoderama** [comment]
It looks like this was done in release 1.2.6.

**Comment by ilyakaznacheev** [comment]
Closed in #71
