### ISSUE TITLE
Value containing `.` always clipped

### ISSUE THREAD

**Issue by stoffeastrom** [ilyakaznacheev/cleanenv#67]
Trying to read a value that contains `.` and it doesn't matter what I set the `env-separator` to. It gets clipped anyway.

Am I using it wrong or this a bug?

**Comment by stoffeastrom** [comment]
This seems to be when reading a `.env` file. Converting to `yaml` and it works

**Comment by ilyakaznacheev** [comment]
Please give some example, I'll check.

**Comment by stoffeastrom** [comment]
Actually, can't reproduce this anymore. I'll reopen with an example if I'm able to reproduce

**Comment by ilyakaznacheev** [comment]
Good luck with that 🙂
