### ISSUE TITLE
this will not work for private attributes

### ISSUE THREAD

**Issue by lukluk** [ilyakaznacheev/cleanenv#68]

**Comment by kz** [comment]
I ran into this problem too, and I notice Kelsey Hightower's envconfig package also does not check whether the field you are attempting to set is unexported. Assuming there is no other case where a developer would set the `env` tag on an unexported field other than intending for that field to be exported, should unexported fields with `env` tags throw errors? (https://groups.google.com/g/golang-nuts/c/i50jwcgHAcs)

**Comment by ilyakaznacheev** [comment]
This is a standard and expected behavior of Golang - library cannot read unexported fields from another package.

The expected behavior it that such fields will be ignored.

**Comment by 838239178** [comment]
@ilyakaznacheev 
```



goroutine 1 [running]:
reflect.valueInterface({0x95f8a0?, 0xc00055c248?, 0xabea8f?}, 0xa?)
        E:/software/dev_core/go1.18.1/src/reflect/value.go:1441 +0xd8
reflect.Value.Interface(...)
        E:/software/dev_core/go1.18.1/src/reflect/value.go:1430
github.com/ilyakaznacheev/cleanenv.readStructMetadata({0x9c7900?, 0xc00055c1c0?})

        E:/text/code-project/GolangProject/pkg/mod/github.com/ilyakaznacheev/cleanenv@v1.3.0/cleanenv.go:274 +0x771
github.com/ilyakaznacheev/cleanenv.readEnvVars({0x9c7900, 0xc00055c1c0}, 0x0)

        E:/text/code-project/GolangProject/pkg/mod/github.com/ilyakaznacheev/cleanenv@v1.3.0/cleanenv.go:333 +0x45
github.com/ilyakaznacheev/cleanenv.ReadConfig({0xace493?, 0xc00041f9a8?}, {0x9c7900, 0xc00055c1c0})


        E:/text/code-project/GolangProject/pkg/mod/github.com/ilyakaznacheev/cleanenv@v1.3.0/cleanenv.go:95 +0x48
```

It doesn't skip unexport field

**Comment by ilyakaznacheev** [comment]
@838239178 can you provide a code example, please?

**Comment by ilyakaznacheev** [comment]
Better create a new issue with an example and detailed error and environment description. Thanks
