### ISSUE TITLE
Not able load the config.yml file

### ISSUE THREAD

**Issue by sriramkp** [ilyakaznacheev/cleanenv#77]
I am new to AWS and Multi Docker Container. 
Not able load config.yml and I don't know how to configure Dockerrun.aws.json to make sure the config.yml file is accessible in the docker container.

```
var err = cleanenv.ReadConfig("config.yml", &cfg)
if err != nil {
	log.Fatal(err)
}
```

**Comment by ilyakaznacheev** [comment]
I'm not sure that the library has something in common with AWS and Multi Docker Container.

Probably you have to copy the config file from the host to the container stage where your CMD or ENTRYPOINT is.

**Comment by ilyakaznacheev** [comment]
You can check if the `config.yml` is present in the desired Docker stage by simply running.
```Dockerfile
RUN cat config.yml
```

As soon it will work, your application will be able to read the file too.

I will close the issue as it is not related to the library itself, but to Docker usage skills, but feel free to tag me in the discussion if you will be ready to provide more examples.
