### ISSUE TITLE
Add a custom error that would provide a meaningful feedback about the parsing issues.

### ISSUE THREAD

**Issue by AM-NiceDay** [ilyakaznacheev/cleanenv#88]
For the following example, if I provide a non-valid `PORT=asd`. Then in the error message, I would see "strconv.ParseInt: parsing "asd": invalid syntax". I think it would be great to have a custom error that would collect and provide some details on the type of error that happened to be able to write it to the log and give corresponding feedback to the runner of the application.

```
type Config struct {
	Web struct {
		Port int `env:"PORT" env-default:"8000"`
	}
}
```

```
if err := cleanenv.ReadEnv(&config); err != nil {
    fmt.Printf("Error: %v", err)
}
```

The message can have the following format: `PORT must be a valid number` or `DB_HOST is a required variable`.

I'm not a Golang developer but have written some code in Go, so if you give your opinion on this and some hints I might be able to implement it and send a PR.

**Comment by ilyakaznacheev** [comment]
Kinda fixed
